from enum import Enum

class Game_State(Enum):
    WELCOME = 1
    NEW_GAME = 2
    MAIN_GAME = 3
    BATTLE = 4
    SHOP = 5
    GAME_OVER = 6
    EXIT = 7

class Battle_Action(Enum):
    HOME = 0
    ATTACK = 1
    DEFEND = 2
    USE_ITEM = 3
    RUN_AWAY = 4
    MONSTER_DEFEATED = 5

class Colors:
    WHITE = (255, 255, 255)
    BLACK = (0, 0, 0)
    GRAY = (200, 200, 200)
    BLUE = (0, 0, 255)
    RED = (255, 0, 0)
    GREEN = (0, 255, 0)
    YELLOW = (255, 255, 0)
    LIGHT_GRAY = (211, 211, 211)
    LIGHT_BLUE = (173, 216, 230)
    LIGHT_RED = (255, 182, 193)
    LIGHT_YELLOW = (255, 255, 224)
    LIGHT_GREEN = (144, 238, 144)
    GOLD = (255, 215, 0)

class Shop_Constants:
    POTION_CARD_KEY = "Potion Card"
    WEAPON_CARD_KEY = "Weapon Card"
    ARMOR_CARD_KEY = "Armor Card"

class Game_Constants:
    SCREEN_WIDTH = 800
    SCREEN_HEIGHT = 600
    POPUP_WIDTH = 400
    POPUP_HEIGHT = 200

    FPS = 60

    # New Game Constants
    NEW_GAME_SPACING = SCREEN_HEIGHT // 30

    NEW_GAME_BUTTON_WIDTH = SCREEN_WIDTH // 8 * 3
    NEW_GAME_BUTTON_HEIGHT = SCREEN_HEIGHT // 12
    NEW_GAME_BUTTON_X = SCREEN_WIDTH // 2 - NEW_GAME_BUTTON_WIDTH // 2
    NEW_GAME_BUTTON_Y = SCREEN_HEIGHT // 2 - NEW_GAME_BUTTON_HEIGHT // 2
    NEW_GAME_BUTTON_INCREMENT = NEW_GAME_BUTTON_HEIGHT + NEW_GAME_SPACING

    # Battle Screen Constants
    BATTLE_SCREEN_SPACING = SCREEN_HEIGHT // 30

    BATTLE_SCREEN_BUTTON_BORDER_X = 0
    BATTLE_SCREEN_BUTTON_BORDER_Y = SCREEN_HEIGHT // 2
    BATTLE_SCREEN_BUTTON_BORDER_HEIGHT = SCREEN_HEIGHT // 2
    BATTLE_SCREEN_BUTTON_BORDER_WIDTH = SCREEN_WIDTH // 8 * 3


    BATTLE_SCREEN_BUTTON_X = BATTLE_SCREEN_BUTTON_BORDER_X + BATTLE_SCREEN_SPACING
    BATTLE_SCREEN_BUTTON_Y = BATTLE_SCREEN_BUTTON_BORDER_Y + BATTLE_SCREEN_SPACING
    BATTLE_SCREEN_BUTTON_HEIGHT = BATTLE_SCREEN_BUTTON_BORDER_HEIGHT // 6
    BATTLE_SCREEN_BUTTON_WIDTH = BATTLE_SCREEN_BUTTON_BORDER_WIDTH - BATTLE_SCREEN_SPACING * 2
    BATTLE_SCREEN_BUTTON_INCREMENT = BATTLE_SCREEN_BUTTON_HEIGHT + BATTLE_SCREEN_SPACING

    BATTLE_SCREEN_LOG_BORDER_X = BATTLE_SCREEN_BUTTON_BORDER_WIDTH
    BATTLE_SCREEN_LOG_BORDER_Y = BATTLE_SCREEN_BUTTON_BORDER_Y
    BATTLE_SCREEN_LOG_BORDER_WIDTH = SCREEN_WIDTH - BATTLE_SCREEN_BUTTON_BORDER_WIDTH
    BATTLE_SCREEN_LOG_BORDER_HEIGHT = BATTLE_SCREEN_BUTTON_BORDER_HEIGHT

    BATTLE_SCREEN_LOG_X = BATTLE_SCREEN_LOG_BORDER_X + BATTLE_SCREEN_SPACING
    BATTLE_SCREEN_LOG_Y = BATTLE_SCREEN_LOG_BORDER_Y + BATTLE_SCREEN_SPACING
    BATTLE_SCREEN_LOG_WIDTH = BATTLE_SCREEN_LOG_BORDER_WIDTH - BATTLE_SCREEN_SPACING * 2
    BATTLE_SCREEN_LOG_HEIGHT = BATTLE_SCREEN_LOG_BORDER_HEIGHT - BATTLE_SCREEN_SPACING * 2